options {
    STATIC = false;
    IGNORE_CASE = true;
    BUILD_PARSER = true;
    LOOKAHEAD = 3;
    FORCE_LA_CHECK = true;
}

PARSER_BEGIN(PascalParser)
package parser;
import java.util.ArrayList;
import parser.ast.*;
public class PascalParser {
    private SymbolTable symbolTable = new SymbolTable();
    private ErrorLog errorLog = new ErrorLog();
    private SemanticStack semanticStack = new SemanticStack();
    private SemanticAnalyzer semanticAnalyzer = new SemanticAnalyzer(symbolTable,semanticStack,errorLog);

    public void printErrors(){
        errorLog.printLog();
    }
}
PARSER_END(PascalParser)

SKIP : {
    " " // Espacios en blanco
  | "\t" // Tabuladores
  | "\n" // Saltos de línea
  | "\r" // Retornos de carro
  | <COMMENT1: "{" (~["}"])* "}">
  | <COMMENT2: "(*" (~["*"])* "*)">
  | <COMMENT3: "//" (~["\n", "\r"])* ("\n" | "\r" | "\r\n")>
}

TOKEN : {
    //Palabras reservadas
       < BEGIN_KEYWORD : "begin" >
      | < END_KEYWORD : "end" >
      | < PROGRAM_KEYWORD : "program" >
      | < VAR_KEYWORD : "var" >
      | < CONST_KEYWORD : "const" >
      //| < LABEL_KEYWORD : "label" >
      //| < FUNCTION_KEYWORD : "function" >
      //| < PROCEDURE_KEYWORD : "procedure" >
      | < ARRAY_KEYWORD : "array" >
      //| < SET_KEYWORD: "set" >
      | < OF_KEYWORD : "of" >
      | < IF_KEYWORD : "if" >
      | < THEN_KEYWORD : "then" >
      | < ELSE_KEYWORD : "else" >
      | < WHILE_KEYWORD : "while" >
      | < DO_KEYWORD : "do" >
      | < FOR_KEYWORD : "for" >
      | < TO_KEYWORD : "to" >
      | < DOWNTO_KEYWORD : "downto" >
      | < REPEAT_KEYWORD : "repeat" >
      | < UNTIL_KEYWORD : "until" >
      //| < CASE_KEYWORD : "case" >
      //| < RECORD_KEYWORD : "record" >
      //| < TYPE_KEYWORD : "type" >
      //| < WITH_KEYWORD : "with" >
      //| < GOTO_KEYWORD : "goto" >
      | < BREAK_KEYWORD : "break" >
      | < CONTINUE_KEYWORD : "continue" >
//      | < EXIT_KEYWORD : "exit" >
      | < OR_KEYWORD : "or" >
      | < AND_KEYWORD : "and" >
      | < NOT_KEYWORD : "not" >
      | < MOD_KEYWORD : "mod" >
      | < DIV_KEYWORD : "div" >
      | <INT_KEYWORD : "integer">
      | <REAL_KEYWORD : "real" >
      | <BOOLEAN_KEYWORD : "boolean" >
      | <CHAR_KEYWORD : "char" >
      | <STRING_KEYWORD  : "string">
      //| <NIL_KEYWORD : "nil" >
      //La palabra reservada packed sirve para optimizar el uso de memoria en arreglos y registros eliminando bytes de relleno
      //| <PACKED_KEYWORD: "packed">
      //| <IN_KEYWORD : "in">
      //| <USES_KEYWORD: "uses">
      | <WRITELN_KEYWORD : "writeln">
      | <WRITE_KEYWORD : "write">
      | <READ_KEYWORD : "read">
      | <READLN_KEYWORD : "readln">
      | <TRUE_KEYWORD : "true">
      | <FALSE_KEYWORD: "false">


  |  < IDENTIFIER : (["a"-"z","A"-"Z"])+ (["a"-"z","A"-"Z","0"-"9"])* >
  | < INTEGER_CONSTANT : (["0"-"9"])+ >
  | < REAL_CONSTANT : (["0"-"9"])+ ("E" ("+" | "-") (["0"-"9"])+  |"." (["0"-"9"])+ | "." (["0"-"9"])+ "E" ("+"|"-") (["0"-"9"])+)>
  | < STRING_CONSTANT : "\'" (~["\'","\n","\r"])* "\'" >
  | <CHAR_CONSTANT : "\'" (~[]) "\'" >
  | < ADD_OP : "+" >
  | < SUB_OP : "-" >
  | < MUL_OP : "*" >
  | < DIV_OP : "/" >
  | < ASSIGN_OP : ":=" >
  | < EQ_OP : "=" >
  | < NEQ_OP : "<>" >
  | < LT_OP : "<" >
  | < GT_OP : ">" >
  | < LE_OP : "<=" >
  | < GE_OP : ">=" >
  | < LPAREN : "(" >
  | < RPAREN : ")" >
  | < LBRACKET : "[">
  | < RBRACKET : "]">
  | < SEMICOLON : ";" >
  | < COLON : ":" >
  | < COMMA : "," >
  | < PERIOD : "." >
  | < RANGE_OP : ".." >
}

Program Program() :
{
    this.semanticStack.pushBlock(BlockType.PROGRAM_BLOCK);
    Token identifier = null;
    ConstBlock constBlock = null;
    VarBlock varBlock = null;
    CodeBlock codeBlock = null;
}
{
  //La gramática comentada acepta la palabra reservada "uses" para importar librerías.
  //<PROGRAM_KEYWORD> <IDENTIFIER> (<LPAREN> <IDENTIFIER> (<COMMA> <IDENTIFIER>)* <RPAREN> )?  <SEMICOLON> (UseStatement())* (Block())+ <PERIOD>
  <PROGRAM_KEYWORD> identifier=<IDENTIFIER>  <SEMICOLON> (VarBlock() | ConstBlock())+ CodeBlock() <PERIOD>

  {this.semanticStack.popBlock();
    return new Program(identifier.image, varBlock, constBlock, codeBlock);
}
}

//void UseStatement():
//{}
//{
//    //La gramatica comentada permite el uso de la clausula uses para importar librerias.
//<USES_KEYWORD> <IDENTIFIER> <SEMICOLON>
//}

void Block():
{}
{
    //La gramatica comentada soporta la creacion de procedimientos y funciones
    //CodeBlock() | ConstBlock()  | VarBlock() | Procedure() | Function()
    CodeBlock() | ConstBlock()  | VarBlock()
}

VarBlock VarBlock() :
{
    this.semanticStack.pushBlock(BlockType.VAR_BLOCK);
    ArrayList<VariableDeclaration> variables= null;
}
{
    <VAR_KEYWORD> (variables=VariableDeclaration())*

    {
        this.semanticStack.popBlock();

        return new VarBlock(variables);
    }
}

ConstBlock ConstBlock() :
{
     semanticStack.pushBlock(BlockType.CONST_BLOCK);
    Token identifier=null,typeIdentifier=null;
    Constant constant=null;
     String constName = "";
     ArrayList<ConstDeclaration> constants = new ArrayList();
}
{
    <CONST_KEYWORD> (
      identifier=<IDENTIFIER> <COLON> typeIdentifier=TypeIdentifier() <EQ_OP> constant=Constant() <SEMICOLON>
      {
              SymbolEntry newConstant = new SymbolEntry(
                      identifier.image,
                      "value",
                      identifier.beginLine,
                      SymbolType.CONSTANT,
                      DataTypes.getDataType(typeIdentifier.image),
                      1,
                      0
              );
              semanticAnalyzer.checkConstantRedefinition(newConstant);
          }
    )*

    {
    semanticStack.popBlock();
    return new ConstBlock(constants);
}
}

void CodeBlock() :
{}
{
  <BEGIN_KEYWORD>
  (Statement())*
  <END_KEYWORD>
}

void Statement() :
{}
{
    //La gramática comentada acepta la llamada a procedimientos y funciones
    //AssignmentStatement() | ProcedureCall() <SEMICOLON> | FunctionCall() <SEMICOLON> | IfStatement() | CaseStatement() | RepeatStatement() | WhileStatement() | ForStatement()
    AssignmentStatement() | ForStatement() | IfStatement() | ReadCall() | ReadlnCall() | WhileStatement() | WriteCall() | WritelnCall()
}

Token TypeIdentifier():
{
    Token type=null;
 }
{
    //La gramatica comentada soporta el uso de tipos definidos por el usuario
    //(<INT_KEYWORD> | <REAL_KEYWORD> | <CHAR_KEYWORD> | <BOOLEAN_KEYWORD> | <IDENTIFIER>) (<LBRACKET> UnsignedNumber() (<COMMA> UnsignedNumber())* <RBRACKET>)?
    (type=<INT_KEYWORD> | type=<REAL_KEYWORD> | type=<CHAR_KEYWORD> | type=<BOOLEAN_KEYWORD> | type=<STRING_KEYWORD>)


    {return type;}
}

//void SimpleType():
//{}
//{
//    <IDENTIFIER>| TypeIdentifier() | <LPAREN> <IDENTIFIER> (<COMMA> <IDENTIFIER> )* <RPAREN> | Constant() (<RANGE_OP> Constant())?
//}

//void FieldList():
//{}
//{
// ( (<IDENTIFIER> (<COMMA> <IDENTIFIER>)* <COLON> Type() <SEMICOLON>)+)?
//}

//void Type():
//{}
//{
//    <ARRAY_KEYWORD> <LBRACKET> SimpleType() <RBRACKET> <OF_KEYWORD> Type() | <RECORD_KEYWORD> FieldList() <END_KEYWORD> <SEMICOLON> | SimpleType()
//}

//void FunctionCall():
//{}
//{
//<IDENTIFIER> ( <LPAREN> Argument() ( <COMMA> Argument() )* <RPAREN>)?
//}

//void ProcedureCall():
//{}
//{
//<IDENTIFIER> ( <LPAREN> Argument() ( <COMMA> Argument() )* <RPAREN>)?
//}

//void Argument():
//{}
//{
//    Expression() | Constant()
//}


Expression Expression():
{
    SimpleExpression left=null,right=null;
    DataType returnType=null;
    Token operator=null;
 }
{
    //La gramatica comentada soporta el uso de la palabra reservada IN para trabajar con conjuntos.
    //SimpleExpression() ((<EQ_OP> | <LT_OP> | <GT_OP> | <NEQ_OP> | <LE_OP> | <GE_OP> | <IN_KEYWORD>) SimpleExpression() )?
    left=SimpleExpression() ((operator=<EQ_OP> |operator=<LT_OP> | operator=<GT_OP> | operator=<NEQ_OP> | operator=<LE_OP> | operator=<GE_OP>) right=SimpleExpression()
    {
        returnType=left.getReturnType();
        if(semanticAnalyzer.checkExpression(left,right,operator.beginLine)){
                returnType = DataType.BOOLEAN;
                return new Expression(returnType,operator.image,left,right);
        }
    }
    )?

    {
    return new Expression(left.getReturnType(),left);
    }
}

SimpleExpression SimpleExpression():
{
    Token sign=null,op=null;
    Term firstTerm = null,curr=null,prev=null;
    ArrayList<Term> otherTerms= new ArrayList<>();
    ArrayList<String> operators = new ArrayList();
    boolean simpleExpressionIsValid=true;
 }
{
    //Solo se incluye "or", "+" y "-" a este nivel
    // por la precedencia de los operadores
    // para el orden de evaluación
    (sign=<ADD_OP> | sign=<SUB_OP>)?
    firstTerm=Term()
    {
        prev=firstTerm;
        if(sign!=null && !semanticAnalyzer.termIsNumeric(firstTerm)){
            errorLog.logSemanticError(sign.beginLine,"No se puede aplicar el signo "+sign.image+" a un valor no numerico");
        }
    }
     ( ( op=<OR_KEYWORD> |op=<ADD_OP> | op=<SUB_OP> ) curr=Term()
        {
            if(op.image.toLowerCase()=="or"){
                if(!semanticAnalyzer.termIsBoolean(prev) || !semanticAnalyzer.termIsBoolean(curr)){
                    errorLog.logSemanticError(op.beginLine,"No se puede aplicar la operacion OR a tipos no booleanos");
                    simpleExpressionIsValid=false;
                }
            }else{
                if(!semanticAnalyzer.termIsNumeric(prev) || !semanticAnalyzer.termIsNumeric(curr)){
                    errorLog.logSemanticError(op.beginLine,"No se puede aplicar la operacion "+op.image+" a tipos no numericos");
                    simpleExpressionIsValid=false;
                }
            }
            operators.add(op.image);
            otherTerms.add(curr);
            prev=curr;
        }
     )*
    {
        if(simpleExpressionIsValid) return new SimpleExpression(firstTerm,otherTerms,operators);
        return new SimpleExpression();
    }
}


Term Term():
{
    Factor firstFactor = null,curr=null,prev=null;
    ArrayList<Factor> otherFactors = new ArrayList<>();
    ArrayList<String> operators = new ArrayList();
    Token op=null;
    boolean termIsValid=true;
}
{
    firstFactor=Factor() {prev=firstFactor;}
    ((op=<MUL_OP> | op=<DIV_OP> | op=<DIV_KEYWORD> |op=<MOD_KEYWORD> | op=<AND_KEYWORD>)
    curr=Factor() {
        if(op.image.toLowerCase() == "and"){
            if(!semanticAnalyzer.factorIsBoolean(prev) || !semanticAnalyzer.factorIsBoolean(curr)){
                errorLog.logSemanticError(op.beginLine,"No se puede aplicar la operacion AND a tipos no booleanos");
                termIsValid=false;
            }
        }else{
            if(!semanticAnalyzer.factorIsNumeric(prev) || !semanticAnalyzer.factorIsNumeric(curr)){
                errorLog.logSemanticError(op.beginLine,"No se puede aplicar la operacion "+op.image+" a tipos no numericos");
                termIsValid=false;
            }
        }
        operators.add(op.image);
        otherFactors.add(curr);
        prev=curr;
    }
    )*

    {
        if(termIsValid) return new Term(firstFactor,operators,otherFactors);
        return new Term();
    }
}

Factor Factor():
{
        Variable variable=null;
        UnsignedConstant unsignedConstant=null;
        Expression expr = null;
        Factor factor = null;
        Token lparen=null,rparen=null;
}
{
    //La gramatica comentada acepta las llamadas a funciones como un factor para una expresion
    //FunctionCall() | <IDENTIFIER>  | Constant() | Variable() | UnsignedConstant() | <LPAREN> Expression() <RPAREN> | <NOT_KEYWORD> Factor() | <LBRACKET> Expression() (<RANGE_OP> Expression())? (<COMMA> Expression() (<RANGE_OP> Expression())?)* <RBRACKET>
     (variable=Variable() {return new Factor(variable);}
    | unsignedConstant=UnsignedConstant() {return new Factor(unsignedConstant);}
    | <LPAREN> expr=Expression() <RPAREN> { return new Factor(expr,(lparen!=null && rparen!=null) ? true:false);}
    | <NOT_KEYWORD> factor=Factor(){return new Factor(factor);})

    {return new Factor();}
}

Constant Constant():
{
    Token sign=null,identifier=null,charConstant=null,stringConstant=null;
    UnsignedNumber unsignedNumber=null;
 }
{
    (
    ((sign=<ADD_OP> | sign=<SUB_OP>)? (

    identifier=<IDENTIFIER>{
        DataType dt = symbolTable.getDataType(identifier.image);
        if(dt!=null && semanticAnalyzer.checkConstant(dt,sign.image,identifier.beginLine)){
            return new Constant(identifier.image,dt,sign.image);
        }
    }
    | unsignedNumber=UnsignedNumber() { return new Constant(unsignedNumber.getValue(),symbolTable.getDataType(identifier.image),sign.image);})
    )
    | charConstant=<CHAR_CONSTANT> {return new Constant(charConstant.image,DataType.CHAR);}
    | stringConstant=<STRING_CONSTANT> {return new Constant(stringConstant.image,DataType.STRING);}
    )

    {return new Constant();}
}


UnsignedConstant UnsignedConstant():
{
   Token identifier=null,charLiteral=null,stringLiteral=null,booleanLiteral=null;
   UnsignedNumber numericLiteral = null;
    String val;DataType type;
}
{
    (identifier=<IDENTIFIER> {
        if(semanticAnalyzer.checkSymbolExists(identifier.image, identifier.beginLine)){
            return new UnsignedConstant(
                identifier.image,
                symbolTable.getDataType(identifier.image)
            );
        }
    }
    | numericLiteral=UnsignedNumber() {return new UnsignedConstant(numericLiteral.getValue(), numericLiteral.getType());}/*| <NIL_KEYWORD> */
    | charLiteral=<CHAR_CONSTANT> {return new UnsignedConstant(charLiteral.image, DataType.CHAR);}
    | stringLiteral=<STRING_CONSTANT> {return new UnsignedConstant(stringLiteral.image,DataType.STRING);})
    | (booleanLiteral=<TRUE_KEYWORD> | booleanLiteral=<FALSE_KEYWORD> ) {return new UnsignedConstant(booleanLiteral.image,DataType.BOOLEAN);}

    {return new UnsignedConstant();}
}

UnsignedNumber UnsignedNumber():
{
    Token numericLiteral;
    DataType dataType;
}
{
    (numericLiteral=<INTEGER_CONSTANT> {dataType = DataType.INTEGER;}
    | numericLiteral=<REAL_CONSTANT> {dataType = DataType.REAL;})

    {return new UnsignedNumber(numericLiteral.image, dataType);}
}

//void RecordReference():
//{}
//{
//    //Esta gramatica soporta la referencia hacia tipos registro.
//    <IDENTIFIER> <PERIOD> (<IDENTIFIER> | ArrayReference() )
//}

Variable Variable():
{
    Token identifier=null;
    Expression expr=null;
}
{
    identifier=<IDENTIFIER>
    (<LBRACKET> expr=Expression() <RBRACKET>
    {
        if(semanticAnalyzer.checkArray(identifier.image,expr,identifier.beginLine)) return new Variable(identifier.image,expr,symbolTable.getDataType(identifier.image));
    }
    )?

    {
        if(semanticAnalyzer.checkSymbolExists(identifier.image,identifier.beginLine)){
            return new Variable(identifier.image,symbolTable.getDataType(identifier.image));
        }
        return new Variable();
    }
}

/*
Las acciones semanticas para la definicion de variables realiza
la comprobacion de la redeclaracion de identificadores.
 */
ArrayList<VariableDeclaration> VariableDeclaration():
{
    this.semanticStack.pushBlock(BlockType.VAR_BLOCK);
    Token name=null,typeIdentifier=null,arrayKeyword=null,arrayLen=null;

    String varValue = "";
    int varDefLine;
    SymbolType varSymbolType = SymbolType.VARIABLE;
    DataType varDataType = null;
    int varLen = 1;
    int varDimension = 0;

    SymbolEntry tmp = new SymbolEntry();
    ArrayList<String> names = new ArrayList();
     ArrayList<VariableDeclaration> variables = new ArrayList<>();
 }
{
    name=<IDENTIFIER>
{
    varDefLine = name.beginLine;
    names.add(name.image);
}
((<COMMA> name=<IDENTIFIER>
{
    names.add(name.image);
} )* <COLON> | <COLON> arrayKeyword=<ARRAY_KEYWORD> <LBRACKET> arrayLen=<INTEGER_CONSTANT> <RBRACKET> <OF_KEYWORD> )

typeIdentifier=TypeIdentifier() <SEMICOLON>
{
    varDataType = DataTypes.getDataType(typeIdentifier.image);
    if(arrayKeyword!=null){
        varSymbolType = SymbolType.ARRAY;
        varLen=Integer.parseInt(arrayLen.image);
        tmp = new SymbolEntry(name.image,varValue,varDefLine,varSymbolType,varDataType,varLen,varDimension);
        semanticAnalyzer.checkArrayRedefinition(tmp);
    }else{
        for(String id: names){
            tmp = new SymbolEntry(id,varValue,varDefLine,varSymbolType,varDataType,varLen,varDimension);
            semanticAnalyzer.checkVariableRedefinition(tmp);
        }
    }
}
//{
//    for(String s:ids){
//        String identifierName = newVariable.image;
//        if(symbolTable.lookSymbol(identifierName)){
//            errorLog.logSemanticError(newVariable.beginLine,"Redeclaracion de la variable "+identifierName);
//        }else{
//            dimension = arrayKeyword != null ? 1:0;
//            len = arraySize!=null ? Integer.parseInt(arraySize.image):0;
//            symbolTable.addSymbol(new SymbolEntry(s,"",typeIdentifier.image, DataTypes.getSize(typeIdentifier.image,len),dimension));
//        }
//    }
//}

{
    this.semanticStack.popBlock();
    return variables;
}
}

//void ParamDefinition():
//{}
//{
//<IDENTIFIER> (<COMMA> <IDENTIFIER> )* <COLON> Type()
//| <FUNCTION_KEYWORD> <IDENTIFIER> (<COMMA> <IDENTIFIER>)* <COLON> Type() <SEMICOLON>
//| <VAR_KEYWORD> <IDENTIFIER> (<COMMA> <IDENTIFIER>)* <COLON> Type()
//| <PROCEDURE_KEYWORD> <IDENTIFIER> (<COMMA> <IDENTIFIER>)*
//}

//void ParamList() :
//{}
//{
//(<LPAREN> ParamDefinition() (<SEMICOLON> ParamDefinition() )* <RPAREN> )?
//}

//void Procedure() :
//{}
//{
// <PROCEDURE_KEYWORD> <IDENTIFIER> ParamList() <SEMICOLON> ( ConstBlock() | VarBlock() )* Block() <SEMICOLON>
//}

//void Function() :
//{}
//{
// <FUNCTION_KEYWORD> <IDENTIFIER> ParamList() <COLON> Type() <SEMICOLON> ( ConstBlock() | VarBlock() )* Block() <SEMICOLON>
//}

void AssignmentStatement():
{
    Variable variable=null;
    Expression expression=null;
}
{
    variable=Variable() <ASSIGN_OP> expression=Expression() <SEMICOLON>
    {
        if(!semanticAnalyzer.checkConstReassignment(variable.getName())){
            //Comprobacion de coincidencia de tipos
        }
    }
}

void IfStatement():
{}
{
    <IF_KEYWORD> Expression() <THEN_KEYWORD> (Statement() | CodeBlock() <SEMICOLON>)  (ElseStatement())?
}

void ElseStatement():
{}
{
    <ELSE_KEYWORD> (Statement() | CodeBlock() <SEMICOLON> )
}

//void CaseStatement():
//{}
//{
//    <CASE_KEYWORD> Expression() <OF_KEYWORD> (Constant() (<COMMA> Constant() )* <COLON> (Statement() | CodeBlock() <SEMICOLON> ))+ <ELSE_KEYWORD> (Statement() | CodeBlock() <SEMICOLON> )<END_KEYWORD> <SEMICOLON>
//}

void WhileStatement():
{}
{
    <WHILE_KEYWORD> Expression() <DO_KEYWORD> (Statement() | CodeBlock() <SEMICOLON> )
}

//void RepeatStatement():
//{}
//{
//    <REPEAT_KEYWORD> (Statement())* <UNTIL_KEYWORD> Expression() <SEMICOLON>
//}

void ForStatement():
{}
{
    <FOR_KEYWORD> <IDENTIFIER> <ASSIGN_OP> Expression() (<DOWNTO_KEYWORD> | <TO_KEYWORD> ) Expression() <DO_KEYWORD> (Statement() | CodeBlock() <SEMICOLON> )
}

void ReadlnCall():
{}
{
    <READLN_KEYWORD> (<LPAREN> (Expression() (<COMMA> Expression() )* )? <RPAREN>)? <SEMICOLON>
}

void ReadCall():
{}
{
    <READ_KEYWORD> (<LPAREN> (Expression() (<COMMA> Expression() )* )? <RPAREN>)? <SEMICOLON>
}

void WritelnCall():
{
    Token lparen=null,semicolon=null,rparen=null;
}
{
        <WRITELN_KEYWORD>
        try{
            (lparen=<LPAREN> (Expression() (<COMMA> Expression() )* )? rparen=<RPAREN>)? semicolon=<SEMICOLON>
        }catch(ParseException paex){
            if(lparen==null){
                errorLog.logSyntaxError(paex.currentToken.endLine,"Se esperaba un \"(\" despues de writeln");
            }
            if(lparen==null){
                errorLog.logSyntaxError(paex.currentToken.endLine,"Se esperaba un \")\" despues de writeln(");
            }
            if(semicolon==null){
                errorLog.logSyntaxError(paex.currentToken.endLine,"Se esperaba un \";\" al final de writeln(...)");
            }
            throw paex;
        }
}

void WriteCall():
{
    Token t=null;
}
{
    <WRITE_KEYWORD> (<LPAREN> (Expression() (<COMMA> Expression() )* )? <RPAREN>)?
    try
    {
        t=<SEMICOLON>

    }catch(ParseException paex){
        if(t==null){
                errorLog.logSyntaxError(paex.currentToken.endLine,"Se esperaba un \";\" al final de write(...)");
        }
        throw paex;
    }
}
