/* PascalParser.java */
/* Generated By:JavaCC: Do not edit this line. PascalParser.java */
package parser;
import java.util.ArrayList;
import parser.ast.*;
import parser.ast.ForStatement.ForMode;
import parser.ast.VariableDeclaration.VariableType;
public class PascalParser implements PascalParserConstants {
    private SymbolTable symbolTable = new SymbolTable();
    private ErrorLog errorLog = new ErrorLog();
    private SemanticStack semanticStack = new SemanticStack();
    private SemanticAnalyzer semanticAnalyzer = new SemanticAnalyzer(symbolTable,semanticStack,errorLog);

    public void printErrors(){
        errorLog.printLog();
    }

    public boolean thereAreErrors(){
        return !errorLog.isEmpty();
    }

  public void printUsages() throws ParseException {System.out.println("Imprimiendo usos");
    symbolTable.printUsages();
  }

  final public Program Program() throws ParseException {this.semanticStack.pushBlock(BlockType.PROGRAM_BLOCK);
    Token identifier = null;
    ConstBlock constBlock = null;
    VarBlock varBlock = null;
    CodeBlock codeBlock = null;
    boolean ok = true;
    try {
      jj_consume_token(PROGRAM_KEYWORD);
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
        ok = false;
    }
    try {
      identifier = jj_consume_token(IDENTIFIER);
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
        ok = false;
    }
    try {
      jj_consume_token(SEMICOLON);
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
        ok = false;
    }
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case CONST_KEYWORD:{
        constBlock = ConstBlock();
if(constBlock!=null){
                  constBlock.attachSymbolTable(symbolTable);
              }
        break;
        }
      default:
        jj_la1[0] = jj_gen;
        ;
      }
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
        ok = false;
    }
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case VAR_KEYWORD:{
        varBlock = VarBlock();
        break;
        }
      default:
        jj_la1[1] = jj_gen;
        ;
      }
if(varBlock!=null){
          varBlock.attachSymbolTable(symbolTable);
        }
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
        ok = false;
    }
    try {
      codeBlock = CodeBlock();
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
        ok = false;
    }
    try {
      jj_consume_token(PERIOD);
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
        ok = false;
    }
if(ok){
        this.semanticStack.popBlock();
        {if ("" != null) return new Program(identifier.image, varBlock, constBlock, codeBlock);}
    }
    {if ("" != null) return new Program();}
    throw new Error("Missing return statement in function");
}

//void UseStatement():
//{}
//{
//    //La gramatica comentada permite el uso de la clausula uses para importar librerias.
//<USES_KEYWORD> <IDENTIFIER> <SEMICOLON>
//}
  final public 
Block Block() throws ParseException {Block block = null;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case BEGIN_KEYWORD:{
        block = CodeBlock();
        break;
        }
      case CONST_KEYWORD:{
        block = ConstBlock();
        break;
        }
      case VAR_KEYWORD:{
        block = VarBlock();
        break;
        }
      default:
        jj_la1[2] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
        {if ("" != null) return new Block();}
    }
{if ("" != null) return block;}
    throw new Error("Missing return statement in function");
}

  final public VarBlock VarBlock() throws ParseException {this.semanticStack.pushBlock(BlockType.VAR_BLOCK);
    ArrayList<VariableDeclaration> variables= new ArrayList<>();
    ArrayList<VariableDeclaration> tmp = null;
    jj_consume_token(VAR_KEYWORD);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[3] = jj_gen;
        break label_1;
      }
      try {
        tmp = VariableDeclaration();
variables.addAll(tmp);
      } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
      }
    }
this.semanticStack.popBlock();
        {if ("" != null) return new VarBlock(variables);}
    throw new Error("Missing return statement in function");
}

  final public ConstBlock ConstBlock() throws ParseException {semanticStack.pushBlock(BlockType.CONST_BLOCK);
    Token identifier=null,typeIdentifier=null;
    Constant constant=null;
     String constName = "";
     SymbolEntry newConstant = null;
     ArrayList<ConstDeclaration> constants = new ArrayList<>();
     boolean ok = true;
    jj_consume_token(CONST_KEYWORD);
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[4] = jj_gen;
        break label_2;
      }
      try {
        identifier = jj_consume_token(IDENTIFIER);
      } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
            ok=false;
      }
      try {
        jj_consume_token(COLON);
      } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
            ok=false;
      }
      try {
        typeIdentifier = TypeIdentifier();
      } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
            ok=false;
      }
      try {
        jj_consume_token(EQ_OP);
      } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
            ok=false;
      }
      try {
        constant = Constant();
      } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
            ok=false;
      }
      try {
        jj_consume_token(SEMICOLON);
      } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
            ok=false;
      }
    }
if(ok){
              newConstant = new SymbolEntry(
                                                      identifier.image,
                                                      constant.getValue(),
                                                      identifier.beginLine,
                                                      SymbolType.CONSTANT,
                                                      DataTypes.getDataType(typeIdentifier.image),
                                                      1,
                                                      0
                                );
            if(!semanticAnalyzer.checkConstantRedefinition(newConstant)){
                symbolTable.addSymbol(newConstant);
                constants.add(new ConstDeclaration(identifier.image,DataTypes.getDataType(typeIdentifier.image),constant.getValue()));
            }

        }
        semanticStack.popBlock();
        {if ("" != null) return new ConstBlock(constants);}
    throw new Error("Missing return statement in function");
}

  final public CodeBlock CodeBlock() throws ParseException {this.semanticStack.pushBlock(BlockType.CODE_BLOCK);
    ArrayList<Statement> statements = new ArrayList<>();
    Statement tmp=null;
    jj_consume_token(BEGIN_KEYWORD);
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF_KEYWORD:
      case WHILE_KEYWORD:
      case FOR_KEYWORD:
      case BREAK_KEYWORD:
      case CONTINUE_KEYWORD:
      case WRITELN_KEYWORD:
      case WRITE_KEYWORD:
      case READ_KEYWORD:
      case READLN_KEYWORD:
      case IDENTIFIER:{
        ;
        break;
        }
      default:
        jj_la1[5] = jj_gen;
        break label_3;
      }
      try {
        tmp = Statement();
statements.add(tmp);
      } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
      }
    }
    try {
      jj_consume_token(END_KEYWORD);
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
    }
this.semanticStack.popBlock();
    {if ("" != null) return new CodeBlock(statements);}
    throw new Error("Missing return statement in function");
}

  final public Statement Statement() throws ParseException {Statement stmt=null;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        stmt = AssignmentStatement();
        break;
        }
      case BREAK_KEYWORD:{
        stmt = BreakStatement();
        break;
        }
      case CONTINUE_KEYWORD:{
        stmt = ContinueStatement();
        break;
        }
      case FOR_KEYWORD:{
        stmt = ForStatement();
        break;
        }
      case IF_KEYWORD:{
        stmt = IfStatement();
        break;
        }
      case READ_KEYWORD:{
        stmt = ReadCall();
        break;
        }
      case READLN_KEYWORD:{
        stmt = ReadlnCall();
        break;
        }
      case WHILE_KEYWORD:{
        stmt = WhileStatement();
        break;
        }
      case WRITE_KEYWORD:{
        stmt = WriteCall();
        break;
        }
      case WRITELN_KEYWORD:{
        stmt = WritelnCall();
        break;
        }
      default:
        jj_la1[6] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
    }
{if ("" != null) return stmt;}
    throw new Error("Missing return statement in function");
}

  final public Token TypeIdentifier() throws ParseException {Token type=null;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INT_KEYWORD:{
        type = jj_consume_token(INT_KEYWORD);
        break;
        }
      case REAL_KEYWORD:{
        type = jj_consume_token(REAL_KEYWORD);
        break;
        }
      case CHAR_KEYWORD:{
        type = jj_consume_token(CHAR_KEYWORD);
        break;
        }
      case BOOLEAN_KEYWORD:{
        type = jj_consume_token(BOOLEAN_KEYWORD);
        break;
        }
      case STRING_KEYWORD:{
        type = jj_consume_token(STRING_KEYWORD);
        break;
        }
      default:
        jj_la1[7] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         {if ("" != null) return new Token();}
    }
{if ("" != null) return type;}
    throw new Error("Missing return statement in function");
}

//void SimpleType():
//{}
//{
//    <IDENTIFIER>| TypeIdentifier() | <LPAREN> <IDENTIFIER> (<COMMA> <IDENTIFIER> )* <RPAREN> | Constant() (<RANGE_OP> Constant())?
//}

//void FieldList():
//{}
//{
// ( (<IDENTIFIER> (<COMMA> <IDENTIFIER>)* <COLON> Type() <SEMICOLON>)+)?
//}

//void Type():
//{}
//{
//    <ARRAY_KEYWORD> <LBRACKET> SimpleType() <RBRACKET> <OF_KEYWORD> Type() | <RECORD_KEYWORD> FieldList() <END_KEYWORD> <SEMICOLON> | SimpleType()
//}

//void FunctionCall():
//{}
//{
//<IDENTIFIER> ( <LPAREN> Argument() ( <COMMA> Argument() )* <RPAREN>)?
//}

//void ProcedureCall():
//{}
//{
//<IDENTIFIER> ( <LPAREN> Argument() ( <COMMA> Argument() )* <RPAREN>)?
//}

//void Argument():
//{}
//{
//    Expression() | Constant()
//}
  final public 

Expression Expression() throws ParseException {SimpleExpression left=null,right=null;
    DataType returnType=null;
    Token operator=null;
    try {
      left = SimpleExpression();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case EQ_OP:
      case NEQ_OP:
      case LT_OP:
      case GT_OP:
      case LE_OP:
      case GE_OP:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case EQ_OP:{
          operator = jj_consume_token(EQ_OP);
          break;
          }
        case LT_OP:{
          operator = jj_consume_token(LT_OP);
          break;
          }
        case GT_OP:{
          operator = jj_consume_token(GT_OP);
          break;
          }
        case NEQ_OP:{
          operator = jj_consume_token(NEQ_OP);
          break;
          }
        case LE_OP:{
          operator = jj_consume_token(LE_OP);
          break;
          }
        case GE_OP:{
          operator = jj_consume_token(GE_OP);
          break;
          }
        default:
          jj_la1[8] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        right = SimpleExpression();
returnType=left.getReturnType();
        if(semanticAnalyzer.checkExpression(left,right,operator.beginLine)){
                returnType = DataType.BOOLEAN;
                {if ("" != null) return new Expression(returnType,operator.image,left,right);}
        }
        break;
        }
      default:
        jj_la1[9] = jj_gen;
        ;
      }
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         {if ("" != null) return new Expression();}
    }
{if ("" != null) return new Expression(left.getReturnType(),left);}
    throw new Error("Missing return statement in function");
}

  final public SimpleExpression SimpleExpression() throws ParseException {Token sign=null,op=null;
    Term firstTerm = null,curr=null,prev=null;
    ArrayList<Term> otherTerms= new ArrayList<>();
    ArrayList<String> operators = new ArrayList<>();
    boolean simpleExpressionIsValid=true;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ADD_OP:
      case SUB_OP:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ADD_OP:{
          sign = jj_consume_token(ADD_OP);
          break;
          }
        case SUB_OP:{
          sign = jj_consume_token(SUB_OP);
          break;
          }
        default:
          jj_la1[10] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      default:
        jj_la1[11] = jj_gen;
        ;
      }
      firstTerm = Term();
prev=firstTerm;
        if(sign!=null && !semanticAnalyzer.termIsNumeric(firstTerm)){
            errorLog.logSemanticError(sign.beginLine,"No se puede aplicar el signo "+sign.image+" a un valor no numerico");
        }
      label_4:
      while (true) {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case OR_KEYWORD:
        case ADD_OP:
        case SUB_OP:{
          ;
          break;
          }
        default:
          jj_la1[12] = jj_gen;
          break label_4;
        }
        try {
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case OR_KEYWORD:{
            op = jj_consume_token(OR_KEYWORD);
            break;
            }
          case ADD_OP:{
            op = jj_consume_token(ADD_OP);
            break;
            }
          case SUB_OP:{
            op = jj_consume_token(SUB_OP);
            break;
            }
          default:
            jj_la1[13] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          curr = Term();
if(op.image.toLowerCase()=="or"){
                if(!semanticAnalyzer.termIsBoolean(prev) || !semanticAnalyzer.termIsBoolean(curr)){
                    errorLog.logSemanticError(op.beginLine,"No se puede aplicar la operacion OR a tipos no booleanos");
                    simpleExpressionIsValid=false;
                }
            }else{
                if(!(semanticAnalyzer.termIsNumeric(prev) && semanticAnalyzer.termIsNumeric(curr))
                && !(semanticAnalyzer.termIsString(prev) && semanticAnalyzer.termIsString(curr))){
                    errorLog.logSemanticError(op.beginLine,"No se puede aplicar la operacion "+op.image+" a tipos "+prev.getReturnType()+","+curr.getReturnType());
                    simpleExpressionIsValid=false;
                }
            }
            operators.add(op.image);
            otherTerms.add(curr);
            prev=curr;
        } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
        }
      }
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
    }
if(simpleExpressionIsValid) {if ("" != null) return new SimpleExpression(firstTerm,otherTerms,operators);}
        {if ("" != null) return new SimpleExpression();}
    throw new Error("Missing return statement in function");
}

  final public Term Term() throws ParseException {Factor firstFactor = null,curr=null,prev=null;
    ArrayList<Factor> otherFactors = new ArrayList<>();
    ArrayList<String> operators = new ArrayList<>();
    Token op=null;
    boolean termIsValid=true;
    try {
      firstFactor = Factor();
prev=firstFactor;
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         {if ("" != null) return new Term();}
    }
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case AND_KEYWORD:
      case MOD_KEYWORD:
      case DIV_KEYWORD:
      case MUL_OP:
      case DIV_OP:{
        ;
        break;
        }
      default:
        jj_la1[14] = jj_gen;
        break label_5;
      }
      try {
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case MUL_OP:{
          op = jj_consume_token(MUL_OP);
          break;
          }
        case DIV_OP:{
          op = jj_consume_token(DIV_OP);
          break;
          }
        case DIV_KEYWORD:{
          op = jj_consume_token(DIV_KEYWORD);
          break;
          }
        case MOD_KEYWORD:{
          op = jj_consume_token(MOD_KEYWORD);
          break;
          }
        case AND_KEYWORD:{
          op = jj_consume_token(AND_KEYWORD);
          break;
          }
        default:
          jj_la1[15] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        curr = Factor();
if(op.image.equalsIgnoreCase("and")){
                 if(!semanticAnalyzer.factorIsBoolean(prev) || !semanticAnalyzer.factorIsBoolean(curr)){
                     errorLog.logSemanticError(op.beginLine,"No se puede aplicar la operacion AND a tipos no booleanos");
                     termIsValid=false;
                 }
             }else{
                 if(!semanticAnalyzer.factorIsNumeric(prev) || !semanticAnalyzer.factorIsNumeric(curr)){
                     errorLog.logSemanticError(op.beginLine,"No se puede aplicar la operacion "+op.image+" a tipos no numericos");
                     termIsValid=false;
                 }
             }
             operators.add(op.image);
             otherFactors.add(curr);
             prev=curr;
      } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
      }
    }
if(termIsValid){
             {if ("" != null) return new Term(firstFactor,operators,otherFactors);}
        }
        {if ("" != null) return new Term();}
    throw new Error("Missing return statement in function");
}

  final public Factor Factor() throws ParseException {Variable variable=null;
        UnsignedConstant unsignedConstant=null;
        Expression expr = null;
        Factor factor = null;
        Token lparen=null,rparen=null,notKeyword=null;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:{
        variable = Variable();
if(variable!=null){
            SymbolEntry tmpSymbol = symbolTable.getSymbol(variable.getName());
            if(tmpSymbol!=null){
                tmpSymbol.addUsage();
            }
         }
         {if ("" != null) return new Factor(variable);}
        break;
        }
      case TRUE_KEYWORD:
      case FALSE_KEYWORD:
      case INTEGER_CONSTANT:
      case REAL_CONSTANT:
      case STRING_CONSTANT:
      case CHAR_CONSTANT:{
        unsignedConstant = UnsignedConstant();
{if ("" != null) return new Factor(unsignedConstant);}
        break;
        }
      case LPAREN:{
        jj_consume_token(LPAREN);
        expr = Expression();
        jj_consume_token(RPAREN);
{if ("" != null) return new Factor(expr,(lparen!=null && rparen!=null) ? true:false);}
        break;
        }
      case NOT_KEYWORD:{
        notKeyword = jj_consume_token(NOT_KEYWORD);
        factor = Factor();
if(notKeyword!=null && factor.getReturnType()!=DataType.BOOLEAN){
        errorLog.logSemanticError(notKeyword.beginLine,"No se puede aplicar el operador NOT a un "+factor.getReturnType());
        {if ("" != null) return new Factor();}
    }
    {if ("" != null) return new Factor(factor,notKeyword!=null ? true:false);}
        break;
        }
      default:
        jj_la1[16] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         {if ("" != null) return new Factor();}
    }
{if ("" != null) return new Factor();}
    throw new Error("Missing return statement in function");
}

  final public Constant Constant() throws ParseException {Token sign=null,identifier=null,charConstant=null,stringConstant=null;
    UnsignedNumber unsignedNumber=null;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IDENTIFIER:
      case INTEGER_CONSTANT:
      case REAL_CONSTANT:
      case ADD_OP:
      case SUB_OP:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case ADD_OP:
        case SUB_OP:{
          switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
          case ADD_OP:{
            sign = jj_consume_token(ADD_OP);
            break;
            }
          case SUB_OP:{
            sign = jj_consume_token(SUB_OP);
            break;
            }
          default:
            jj_la1[17] = jj_gen;
            jj_consume_token(-1);
            throw new ParseException();
          }
          break;
          }
        default:
          jj_la1[18] = jj_gen;
          ;
        }
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFIER:{
          identifier = jj_consume_token(IDENTIFIER);
if(identifier!=null){
            DataType dt = symbolTable.getDataType(identifier.image);
            if(dt!=null && semanticAnalyzer.checkConstant(dt,sign.image,identifier.beginLine)){
                {if ("" != null) return new Constant(identifier.image,dt,sign.image);}
            }
        }
          break;
          }
        case INTEGER_CONSTANT:
        case REAL_CONSTANT:{
          unsignedNumber = UnsignedNumber();
{if ("" != null) return new Constant(unsignedNumber.getValue(),unsignedNumber.getType(),sign!=null ? sign.image:null);}
          break;
          }
        default:
          jj_la1[19] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        break;
        }
      case CHAR_CONSTANT:{
        charConstant = jj_consume_token(CHAR_CONSTANT);
{if ("" != null) return new Constant(charConstant.image,DataType.CHAR);}
        break;
        }
      case STRING_CONSTANT:{
        stringConstant = jj_consume_token(STRING_CONSTANT);
{if ("" != null) return new Constant(stringConstant.image,DataType.STRING);}
        break;
        }
      default:
        jj_la1[20] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         {if ("" != null) return new Constant();}
    }
{if ("" != null) return new Constant();}
    throw new Error("Missing return statement in function");
}

  final public UnsignedConstant UnsignedConstant() throws ParseException {Token identifier=null,charLiteral=null,stringLiteral=null,booleanLiteral=null;
   UnsignedNumber numericLiteral = null;
    String val;DataType type;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INTEGER_CONSTANT:
      case REAL_CONSTANT:{
        //    identifier=<IDENTIFIER> {
        //        if(semanticAnalyzer.checkSymbolExists(identifier.image, identifier.beginLine)){
        //            return new UnsignedConstant(
        //                identifier.image,
        //                symbolTable.getDataType(identifier.image)
        //            );
        //        }
        //    }
            numericLiteral = UnsignedNumber();
{if ("" != null) return new UnsignedConstant(numericLiteral.getValue(), numericLiteral.getType());}
        break;
        }
      case CHAR_CONSTANT:{
        charLiteral = jj_consume_token(CHAR_CONSTANT);
{if ("" != null) return new UnsignedConstant(charLiteral.image, DataType.CHAR);}
        break;
        }
      case STRING_CONSTANT:{
        stringLiteral = jj_consume_token(STRING_CONSTANT);
{if ("" != null) return new UnsignedConstant(stringLiteral.image,DataType.STRING);}
        break;
        }
      case TRUE_KEYWORD:
      case FALSE_KEYWORD:{
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case TRUE_KEYWORD:{
          booleanLiteral = jj_consume_token(TRUE_KEYWORD);
          break;
          }
        case FALSE_KEYWORD:{
          booleanLiteral = jj_consume_token(FALSE_KEYWORD);
          break;
          }
        default:
          jj_la1[21] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
{if ("" != null) return new UnsignedConstant(booleanLiteral.image,DataType.BOOLEAN);}
        break;
        }
      default:
        jj_la1[22] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         {if ("" != null) return new UnsignedConstant();}
    }
{if ("" != null) return new UnsignedConstant();}
    throw new Error("Missing return statement in function");
}

  final public UnsignedNumber UnsignedNumber() throws ParseException {Token numericLiteral=null;
    DataType dataType=null;
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case INTEGER_CONSTANT:{
        numericLiteral = jj_consume_token(INTEGER_CONSTANT);
dataType = DataType.INTEGER;
        break;
        }
      case REAL_CONSTANT:{
        numericLiteral = jj_consume_token(REAL_CONSTANT);
dataType = DataType.REAL;
        break;
        }
      default:
        jj_la1[23] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         {if ("" != null) return new UnsignedNumber();}
    }
{if ("" != null) return new UnsignedNumber(numericLiteral.image, dataType);}
    throw new Error("Missing return statement in function");
}

//void RecordReference():
//{}
//{
//    //Esta gramatica soporta la referencia hacia tipos registro.
//    <IDENTIFIER> <PERIOD> (<IDENTIFIER> | ArrayReference() )
//}
  final public 
Variable Variable() throws ParseException {Token identifier=null;
    Expression expr=null;
    try {
      identifier = jj_consume_token(IDENTIFIER);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LBRACKET:{
        jj_consume_token(LBRACKET);
        expr = Expression();
        jj_consume_token(RBRACKET);
if(semanticAnalyzer.checkArray(identifier.image,expr,identifier.beginLine)) {if ("" != null) return new Variable(identifier.image,expr,symbolTable.getDataType(identifier.image));}
        break;
        }
      default:
        jj_la1[24] = jj_gen;
        ;
      }
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         {if ("" != null) return new Variable();}
    }
if(semanticAnalyzer.checkSymbolExists(identifier.image,identifier.beginLine)){
            {if ("" != null) return new Variable(identifier.image,symbolTable.getDataType(identifier.image));}
        }
        {if ("" != null) return new Variable();}
    throw new Error("Missing return statement in function");
}

/*
Las acciones semanticas para la definicion de variables realiza
la comprobacion de la redeclaracion de identificadores.
 */
  final public ArrayList<VariableDeclaration> VariableDeclaration() throws ParseException {this.semanticStack.pushBlock(BlockType.VAR_BLOCK);
    Token name=null,typeIdentifier=null,arrayKeyword=null,arrayLen=null;

    int varDefLine=0;
    SymbolType varSymbolType = SymbolType.VARIABLE;
    DataType varDataType = null;
    int varLen = 1;
    int varDimension = 0;

    SymbolEntry tmp = new SymbolEntry();
    ArrayList<String> names = new ArrayList<>();
    ArrayList<VariableDeclaration> variables = new ArrayList<>();
    boolean ok = true;
    try {
      name = jj_consume_token(IDENTIFIER);
varDefLine = name.beginLine;
        names.add(name.image);
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
        ok = false;
    }
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case COMMA:{
        ;
        break;
        }
      default:
        jj_la1[25] = jj_gen;
        break label_6;
      }
      try {
        jj_consume_token(COMMA);
      } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
            ok = false;
      }
      try {
        name = jj_consume_token(IDENTIFIER);
names.add(name.image);
      } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
            ok = false;
      }
    }
    try {
      jj_consume_token(COLON);
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         ok = false;
    }
    switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
    case ARRAY_KEYWORD:{
      try {
        arrayKeyword = jj_consume_token(ARRAY_KEYWORD);
      } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         ok = false;
      }
      try {
        jj_consume_token(LBRACKET);
      } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         ok = false;
      }
      try {
        arrayLen = jj_consume_token(INTEGER_CONSTANT);
      } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         ok = false;
      }
      try {
        jj_consume_token(RBRACKET);
      } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         ok = false;
      }
      try {
        jj_consume_token(OF_KEYWORD);
      } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         ok = false;
      }
      break;
      }
    default:
      jj_la1[26] = jj_gen;
      ;
    }
    try {
      typeIdentifier = TypeIdentifier();
varDataType = DataTypes.getDataType(typeIdentifier.image);
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
        ok = false;
    }
    try {
      jj_consume_token(SEMICOLON);
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
        ok = false;
    }
if(ok){
            if(arrayKeyword!=null){
                varSymbolType = SymbolType.ARRAY;
                varLen=Integer.parseInt(arrayLen.image);
                tmp = new SymbolEntry(name.image,null,varDefLine,varSymbolType,varDataType,varLen,varDimension);
                if(!semanticAnalyzer.checkArrayRedefinition(tmp)){
                    variables.add(new VariableDeclaration(name.image,DataTypes.getDataType(typeIdentifier.image),Integer.parseInt(arrayLen.image)));
                    symbolTable.addSymbol(tmp);
                }
            }else{
                for(String id: names){
                    tmp = new SymbolEntry(id,null,varDefLine,varSymbolType,varDataType,varLen,varDimension);
                    if(!semanticAnalyzer.checkVariableRedefinition(tmp)){
                        variables.add(new VariableDeclaration(id,DataTypes.getDataType(typeIdentifier.image)));
                        symbolTable.addSymbol(tmp);
                    }
                }
            }
        }
        this.semanticStack.popBlock();
          {if ("" != null) return variables;}
    throw new Error("Missing return statement in function");
}

//void ParamDefinition():
//{}
//{
//<IDENTIFIER> (<COMMA> <IDENTIFIER> )* <COLON> Type()
//| <FUNCTION_KEYWORD> <IDENTIFIER> (<COMMA> <IDENTIFIER>)* <COLON> Type() <SEMICOLON>
//| <VAR_KEYWORD> <IDENTIFIER> (<COMMA> <IDENTIFIER>)* <COLON> Type()
//| <PROCEDURE_KEYWORD> <IDENTIFIER> (<COMMA> <IDENTIFIER>)*
//}

//void ParamList() :
//{}
//{
//(<LPAREN> ParamDefinition() (<SEMICOLON> ParamDefinition() )* <RPAREN> )?
//}

//void Procedure() :
//{}
//{
// <PROCEDURE_KEYWORD> <IDENTIFIER> ParamList() <SEMICOLON> ( ConstBlock() | VarBlock() )* Block() <SEMICOLON>
//}

//void Function() :
//{}
//{
// <FUNCTION_KEYWORD> <IDENTIFIER> ParamList() <COLON> Type() <SEMICOLON> ( ConstBlock() | VarBlock() )* Block() <SEMICOLON>
//}
  final public 
AssignmentStatement AssignmentStatement() throws ParseException {Variable variable=null;
    Expression expression=null;
    Token assignmentOp=null;
    boolean ok = true;
    try {
      variable = Variable();
    } catch (ParseException paex) {
ok = false;
         errorLog.logSyntaxError(paex);
    }
    try {
      assignmentOp = jj_consume_token(ASSIGN_OP);
if(assignmentOp!=null && semanticAnalyzer.checkConstReassignment(variable.getName())){
                errorLog.logSemanticError(assignmentOp.beginLine, "Rasignacion de constante "+variable.getName());
            }
    } catch (ParseException paex) {
ok = false;
      errorLog.logSyntaxError(paex);
    }
    try {
      expression = Expression();
if(assignmentOp!=null && !semanticAnalyzer.checkAssignment(variable,expression)){
                errorLog.logSemanticError(assignmentOp.beginLine, "No se puede asignar un "+expression.getReturnType()+" a un "+variable.getDataType());
            }
    } catch (ParseException paex) {
ok = false;
      errorLog.logSyntaxError(paex);
    }
    try {
      jj_consume_token(SEMICOLON);
    } catch (ParseException paex) {
ok = false;
      errorLog.logSyntaxError(paex);
    }
if(ok){
            {if ("" != null) return new AssignmentStatement(variable,expression);}
        }
        {if ("" != null) return new AssignmentStatement();}
    throw new Error("Missing return statement in function");
}

  final public IfStatement IfStatement() throws ParseException {semanticStack.pushBlock(BlockType.IF_BLOCK);
        Expression expr=null;
        Token ifKeyword=null;
        Statement stmt=null;
        CodeBlock codeBlock=null;
        ElseStatement elseStmt=null;
    try {
      ifKeyword = jj_consume_token(IF_KEYWORD);
      expr = Expression();
if(expr.getReturnType()!=DataType.BOOLEAN){
            errorLog.logSemanticError(ifKeyword.beginLine, "Se asigno una expresion no BOOLEANA al bloque IF");
            {if ("" != null) return new IfStatement();}
        }
      jj_consume_token(THEN_KEYWORD);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF_KEYWORD:
      case WHILE_KEYWORD:
      case FOR_KEYWORD:
      case BREAK_KEYWORD:
      case CONTINUE_KEYWORD:
      case WRITELN_KEYWORD:
      case WRITE_KEYWORD:
      case READ_KEYWORD:
      case READLN_KEYWORD:
      case IDENTIFIER:{
        stmt = Statement();
        break;
        }
      case BEGIN_KEYWORD:{
        codeBlock = CodeBlock();
        jj_consume_token(SEMICOLON);
        break;
        }
      default:
        jj_la1[27] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case ELSE_KEYWORD:{
        elseStmt = ElseStatement();
        break;
        }
      default:
        jj_la1[28] = jj_gen;
        ;
      }
semanticStack.popBlock();
        if(elseStmt==null){
            if(stmt!=null) {if ("" != null) return new IfStatement(expr,stmt);}
            {if ("" != null) return new IfStatement(expr,codeBlock);}
        }
        if(stmt!=null) {if ("" != null) return new IfStatement(expr,stmt,elseStmt);}
        {if ("" != null) return new IfStatement(expr,codeBlock,elseStmt);}
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         {if ("" != null) return new IfStatement();}
    }
    throw new Error("Missing return statement in function");
}

  final public ElseStatement ElseStatement() throws ParseException {semanticStack.pushBlock(BlockType.ELSE_BLOCK);
        Statement statement=null;CodeBlock codeBlock=null;
    jj_consume_token(ELSE_KEYWORD);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF_KEYWORD:
      case WHILE_KEYWORD:
      case FOR_KEYWORD:
      case BREAK_KEYWORD:
      case CONTINUE_KEYWORD:
      case WRITELN_KEYWORD:
      case WRITE_KEYWORD:
      case READ_KEYWORD:
      case READLN_KEYWORD:
      case IDENTIFIER:{
        statement = Statement();
        break;
        }
      case BEGIN_KEYWORD:{
        codeBlock = CodeBlock();
        jj_consume_token(SEMICOLON);
        break;
        }
      default:
        jj_la1[29] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
    }
semanticStack.popBlock();
        if(statement!=null){if ("" != null) return new ElseStatement(statement);}
        if(codeBlock!=null){if ("" != null) return new ElseStatement(codeBlock);}
        {if ("" != null) return new ElseStatement();}
    throw new Error("Missing return statement in function");
}

//void CaseStatement():
//{}
//{
//    <CASE_KEYWORD> Expression() <OF_KEYWORD> (Constant() (<COMMA> Constant() )* <COLON> (Statement() | CodeBlock() <SEMICOLON> ))+ <ELSE_KEYWORD> (Statement() | CodeBlock() <SEMICOLON> )<END_KEYWORD> <SEMICOLON>
//}
  final public 
WhileStatement WhileStatement() throws ParseException {semanticStack.pushBlock(BlockType.WHILE_BLOCK);
    Expression expr=null;
    Token whileKeyword=null;
    Statement stmt=null;
    CodeBlock codeBlock=null;
    whileKeyword = jj_consume_token(WHILE_KEYWORD);
    try {
      expr = Expression();
if(expr.getReturnType()!=DataType.BOOLEAN){
                errorLog.logSemanticError(whileKeyword.beginLine,"Se asigno una expresion no BOOLEANA al bloque WHILE");
            }
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
    }
    try {
      jj_consume_token(DO_KEYWORD);
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
    }
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF_KEYWORD:
      case WHILE_KEYWORD:
      case FOR_KEYWORD:
      case BREAK_KEYWORD:
      case CONTINUE_KEYWORD:
      case WRITELN_KEYWORD:
      case WRITE_KEYWORD:
      case READ_KEYWORD:
      case READLN_KEYWORD:
      case IDENTIFIER:{
        stmt = Statement();
        break;
        }
      case BEGIN_KEYWORD:{
        codeBlock = CodeBlock();
        try {
          jj_consume_token(SEMICOLON);
        } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
        }
        break;
        }
      default:
        jj_la1[30] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
    }
semanticStack.popBlock();
     if(stmt!=null){if ("" != null) return new WhileStatement(expr,stmt);}
     if(codeBlock!=null){if ("" != null) return new WhileStatement(expr,codeBlock);}
     {if ("" != null) return new WhileStatement();}
    throw new Error("Missing return statement in function");
}

//void RepeatStatement():
//{}
//{
//    <REPEAT_KEYWORD> (Statement())* <UNTIL_KEYWORD> Expression() <SEMICOLON>
//}
  final public 
ForStatement ForStatement() throws ParseException {semanticStack.pushBlock(BlockType.FOR_BLOCK);
        Expression expr=null,expr2=null;
        Token forKeyword=null;
        Variable variable = null;
        Token mode = null;
        Statement stmt=null;
        CodeBlock codeBlock=null;
    try {
      forKeyword = jj_consume_token(FOR_KEYWORD);
      variable = Variable();
      jj_consume_token(ASSIGN_OP);
      expr = Expression();
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case DOWNTO_KEYWORD:{
        mode = jj_consume_token(DOWNTO_KEYWORD);
        break;
        }
      case TO_KEYWORD:{
        mode = jj_consume_token(TO_KEYWORD);
        break;
        }
      default:
        jj_la1[31] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      expr2 = Expression();
      jj_consume_token(DO_KEYWORD);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case IF_KEYWORD:
      case WHILE_KEYWORD:
      case FOR_KEYWORD:
      case BREAK_KEYWORD:
      case CONTINUE_KEYWORD:
      case WRITELN_KEYWORD:
      case WRITE_KEYWORD:
      case READ_KEYWORD:
      case READLN_KEYWORD:
      case IDENTIFIER:{
        stmt = Statement();
        break;
        }
      case BEGIN_KEYWORD:{
        codeBlock = CodeBlock();
        jj_consume_token(SEMICOLON);
        break;
        }
      default:
        jj_la1[32] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
if(!semanticAnalyzer.checkConstReassignment(variable.getName())
    && variable.getDataType()==DataType.INTEGER
    && symbolTable.getSymbolType(variable.getName())!=SymbolType.ARRAY
    && semanticAnalyzer.checkAssignment(variable,expr)
    && expr2.getReturnType()==DataType.INTEGER
    ){
        ForMode forMode=mode.image.toLowerCase().toLowerCase().equals("to") ? ForMode.TO:ForMode.DOWNTO;
        semanticStack.popBlock();
        if(stmt!=null) {if ("" != null) return new ForStatement(variable,expr,forMode,expr2,stmt);}
        {if ("" != null) return new ForStatement(variable,expr,forMode,expr2,codeBlock);}
    }
    semanticStack.popBlock();
    {if ("" != null) return new ForStatement();}
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
             {if ("" != null) return new ForStatement();}
    }
    throw new Error("Missing return statement in function");
}

  final public BreakStatement BreakStatement() throws ParseException {Token keyword=null;
    try {
      keyword = jj_consume_token(BREAK_KEYWORD);
      jj_consume_token(SEMICOLON);
if(keyword!=null && !semanticAnalyzer.checkInsideLoop()){
            errorLog.logSemanticError(keyword.beginLine,"Sentencia "+keyword.image+" fuera de un ciclo");
            {if ("" != null) return null;}
        }
        {if ("" != null) return new BreakStatement();}
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         {if ("" != null) return new BreakStatement();}
    }
    throw new Error("Missing return statement in function");
}

  final public ContinueStatement ContinueStatement() throws ParseException {Token keyword=null;
    try {
      keyword = jj_consume_token(CONTINUE_KEYWORD);
      jj_consume_token(SEMICOLON);
if(keyword!=null && !semanticAnalyzer.checkInsideLoop()){
            errorLog.logSemanticError(keyword.beginLine,"Sentencia "+keyword.image+" fuera de un ciclo");
            {if ("" != null) return null;}
        }
        {if ("" != null) return new ContinueStatement();}
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         {if ("" != null) return new ContinueStatement();}
    }
    throw new Error("Missing return statement in function");
}

  final public ReadlnCall ReadlnCall() throws ParseException {ArrayList<Variable> variables = new ArrayList<>();
 Variable tmp = null;
    try {
      jj_consume_token(READLN_KEYWORD);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LPAREN:{
        jj_consume_token(LPAREN);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFIER:{
          tmp = Variable();
variables.add(tmp);
          label_7:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case COMMA:{
              ;
              break;
              }
            default:
              jj_la1[33] = jj_gen;
              break label_7;
            }
            try {
              jj_consume_token(COMMA);
              tmp = Variable();
variables.add(tmp);
            } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
            }
          }
          break;
          }
        default:
          jj_la1[34] = jj_gen;
          ;
        }
        jj_consume_token(RPAREN);
        break;
        }
      default:
        jj_la1[35] = jj_gen;
        ;
      }
      jj_consume_token(SEMICOLON);
{if ("" != null) return new ReadlnCall(variables);}
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         {if ("" != null) return new ReadlnCall();}
    }
    throw new Error("Missing return statement in function");
}

  final public ReadCall ReadCall() throws ParseException {ArrayList<Variable> variables = new ArrayList<>();
    Variable tmp=null;
    try {
      jj_consume_token(READ_KEYWORD);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LPAREN:{
        jj_consume_token(LPAREN);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case IDENTIFIER:{
          tmp = Variable();
variables.add(tmp);
          label_8:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case COMMA:{
              ;
              break;
              }
            default:
              jj_la1[36] = jj_gen;
              break label_8;
            }
            try {
              jj_consume_token(COMMA);
              tmp = Variable();
variables.add(tmp);
            } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
            }
          }
          break;
          }
        default:
          jj_la1[37] = jj_gen;
          ;
        }
        jj_consume_token(RPAREN);
        break;
        }
      default:
        jj_la1[38] = jj_gen;
        ;
      }
      jj_consume_token(SEMICOLON);
{if ("" != null) return new ReadCall(variables);}
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         {if ("" != null) return new ReadCall();}
    }
    throw new Error("Missing return statement in function");
}

  final public WritelnCall WritelnCall() throws ParseException {Token lparen=null,semicolon=null,rparen=null;
    ArrayList<Expression> expressions = new ArrayList<>();
    Expression tmp = null;
    jj_consume_token(WRITELN_KEYWORD);
    try {
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LPAREN:{
        lparen = jj_consume_token(LPAREN);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NOT_KEYWORD:
        case TRUE_KEYWORD:
        case FALSE_KEYWORD:
        case IDENTIFIER:
        case INTEGER_CONSTANT:
        case REAL_CONSTANT:
        case STRING_CONSTANT:
        case CHAR_CONSTANT:
        case ADD_OP:
        case SUB_OP:
        case LPAREN:{
          tmp = Expression();
expressions.add(tmp);
          label_9:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case COMMA:{
              ;
              break;
              }
            default:
              jj_la1[39] = jj_gen;
              break label_9;
            }
            try {
              jj_consume_token(COMMA);
              tmp = Expression();
expressions.add(tmp);
            } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
            }
          }
          break;
          }
        default:
          jj_la1[40] = jj_gen;
          ;
        }
        rparen = jj_consume_token(RPAREN);
        break;
        }
      default:
        jj_la1[41] = jj_gen;
        ;
      }
      semicolon = jj_consume_token(SEMICOLON);
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
             {if ("" != null) return new WritelnCall();}
    }
{if ("" != null) return new WritelnCall(expressions);}
    throw new Error("Missing return statement in function");
}

  final public WriteCall WriteCall() throws ParseException {Token t=null;
    ArrayList<Expression> expressions = new ArrayList<>();
    Expression tmp = null;
    try {
      jj_consume_token(WRITE_KEYWORD);
      switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
      case LPAREN:{
        jj_consume_token(LPAREN);
        switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
        case NOT_KEYWORD:
        case TRUE_KEYWORD:
        case FALSE_KEYWORD:
        case IDENTIFIER:
        case INTEGER_CONSTANT:
        case REAL_CONSTANT:
        case STRING_CONSTANT:
        case CHAR_CONSTANT:
        case ADD_OP:
        case SUB_OP:
        case LPAREN:{
          tmp = Expression();
expressions.add(tmp);
          label_10:
          while (true) {
            switch ((jj_ntk==-1)?jj_ntk_f():jj_ntk) {
            case COMMA:{
              ;
              break;
              }
            default:
              jj_la1[42] = jj_gen;
              break label_10;
            }
            try {
              jj_consume_token(COMMA);
              tmp = Expression();
expressions.add(tmp);
            } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
            }
          }
          break;
          }
        default:
          jj_la1[43] = jj_gen;
          ;
        }
        jj_consume_token(RPAREN);
        break;
        }
      default:
        jj_la1[44] = jj_gen;
        ;
      }
      t = jj_consume_token(SEMICOLON);
    } catch (ParseException paex) {
errorLog.logSyntaxError(paex);
         {if ("" != null) return new WriteCall();}
    }
{if ("" != null) return new WriteCall(expressions);}
    throw new Error("Missing return statement in function");
}

  /** Generated Token Manager. */
  public PascalParserTokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private int jj_gen;
  final private int[] jj_la1 = new int[45];
  static private int[] jj_la1_0;
  static private int[] jj_la1_1;
  static private int[] jj_la1_2;
  static {
	   jj_la1_init_0();
	   jj_la1_init_1();
	   jj_la1_init_2();
	}
	private static void jj_la1_init_0() {
	   jj_la1_0 = new int[] {0x1000,0x800,0x1900,0x0,0x0,0x6148000,0x6148000,0x0,0x0,0x0,0x0,0x0,0x8000000,0x8000000,0xd0000000,0xd0000000,0x20000000,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x2000,0x6148100,0x20000,0x6148100,0x6148100,0x600000,0x6148100,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x20000000,0x0,0x0,0x20000000,0x0,};
	}
	private static void jj_la1_init_1() {
	   jj_la1_1 = new int[] {0x0,0x0,0x0,0x800,0x800,0x9e0,0x9e0,0x1f,0x7e00000,0x7e00000,0x30000,0x30000,0x30000,0x30000,0xc0000,0xc0000,0x800fe00,0x30000,0x30000,0x3800,0x3f800,0x600,0xf600,0x3000,0x20000000,0x0,0x0,0x9e0,0x0,0x9e0,0x9e0,0x0,0x9e0,0x0,0x800,0x8000000,0x0,0x800,0x8000000,0x0,0x803fe00,0x8000000,0x0,0x803fe00,0x8000000,};
	}
	private static void jj_la1_init_2() {
	   jj_la1_2 = new int[] {0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x0,0x0,0x0,0x0,0x0,0x2,0x0,0x0,0x2,0x0,0x0,0x2,0x0,0x0,0x2,0x0,0x0,};
	}

  /** Constructor with InputStream. */
  public PascalParser(java.io.InputStream stream) {
	  this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public PascalParser(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source = new PascalParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 45; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
	  ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
	 try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 45; i++) jj_la1[i] = -1;
  }

  /** Constructor. */
  public PascalParser(java.io.Reader stream) {
	 jj_input_stream = new SimpleCharStream(stream, 1, 1);
	 token_source = new PascalParserTokenManager(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 45; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
	if (jj_input_stream == null) {
	   jj_input_stream = new SimpleCharStream(stream, 1, 1);
	} else {
	   jj_input_stream.ReInit(stream, 1, 1);
	}
	if (token_source == null) {
 token_source = new PascalParserTokenManager(jj_input_stream);
	}

	 token_source.ReInit(jj_input_stream);
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 45; i++) jj_la1[i] = -1;
  }

  /** Constructor with generated Token Manager. */
  public PascalParser(PascalParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 45; i++) jj_la1[i] = -1;
  }

  /** Reinitialise. */
  public void ReInit(PascalParserTokenManager tm) {
	 token_source = tm;
	 token = new Token();
	 jj_ntk = -1;
	 jj_gen = 0;
	 for (int i = 0; i < 45; i++) jj_la1[i] = -1;
  }

  private Token jj_consume_token(int kind) throws ParseException {
	 Token oldToken;
	 if ((oldToken = token).next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 if (token.kind == kind) {
	   jj_gen++;
	   return token;
	 }
	 token = oldToken;
	 jj_kind = kind;
	 throw generateParseException();
  }


/** Get the next Token. */
  final public Token getNextToken() {
	 if (token.next != null) token = token.next;
	 else token = token.next = token_source.getNextToken();
	 jj_ntk = -1;
	 jj_gen++;
	 return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
	 Token t = token;
	 for (int i = 0; i < index; i++) {
	   if (t.next != null) t = t.next;
	   else t = t.next = token_source.getNextToken();
	 }
	 return t;
  }

  private int jj_ntk_f() {
	 if ((jj_nt=token.next) == null)
	   return (jj_ntk = (token.next=token_source.getNextToken()).kind);
	 else
	   return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;

  /** Generate ParseException. */
  public ParseException generateParseException() {
	 jj_expentries.clear();
	 boolean[] la1tokens = new boolean[68];
	 if (jj_kind >= 0) {
	   la1tokens[jj_kind] = true;
	   jj_kind = -1;
	 }
	 for (int i = 0; i < 45; i++) {
	   if (jj_la1[i] == jj_gen) {
		 for (int j = 0; j < 32; j++) {
		   if ((jj_la1_0[i] & (1<<j)) != 0) {
			 la1tokens[j] = true;
		   }
		   if ((jj_la1_1[i] & (1<<j)) != 0) {
			 la1tokens[32+j] = true;
		   }
		   if ((jj_la1_2[i] & (1<<j)) != 0) {
			 la1tokens[64+j] = true;
		   }
		 }
	   }
	 }
	 for (int i = 0; i < 68; i++) {
	   if (la1tokens[i]) {
		 jj_expentry = new int[1];
		 jj_expentry[0] = i;
		 jj_expentries.add(jj_expentry);
	   }
	 }
	 int[][] exptokseq = new int[jj_expentries.size()][];
	 for (int i = 0; i < jj_expentries.size(); i++) {
	   exptokseq[i] = jj_expentries.get(i);
	 }
	 return new ParseException(token, exptokseq, tokenImage);
  }

  private boolean trace_enabled;

/** Trace enabled. */
  final public boolean trace_enabled() {
	 return trace_enabled;
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

}
